"""Edge-Opt public package API."""

from .activation import (
    ActivationStatisticsCollector,
    ActivationStatisticsTable,
    ChannelStatistics,
    ChannelStatsObserver,
)
from .comparison import StrategyComparison, StrategyMeasurement
from .core import DType, ModelSpec, OperatorKind, OperatorSpec, TensorSpec
from .errors import AccuracyBudgetExceeded, ConfigurationError, EdgeOptError
from .hardware import (
    BUILTIN_PROFILES,
    HardwareProfile,
    MemoryTier,
    SparseComputeCapability,
    load_builtin_profile,
)
from .pipeline import (
    OptimizationConfig,
    OptimizationPipeline,
    OptimizationResult,
    QualityAssessment,
    QualityConstraint,
    optimize_model_spec,
)
from .profiling import (
    BenchmarkResult,
    ModelProfile,
    OperatorProfile,
    RooflineProfiler,
    benchmark_callable,
    operator_flops,
)
from .pruning import (
    MagnitudePruner,
    PolynomialPruningSchedule,
    PruningStepResult,
    estimate_sparse_storage,
    measured_sparsity,
)
from .quantization import (
    CalibrationTable,
    EntropyObserver,
    MinMaxObserver,
    QuantizationConfig,
    QuantizationParams,
    RepresentativeCalibrator,
    dequantize,
    fake_quantize,
    quantize,
)
from .smoothquant import (
    SmoothQuantConfig,
    SmoothQuantResult,
    apply_smoothquant,
    smoothquant_scales,
)
from .structured import NMPruner, NMPruningPattern, NMPruningResult, nm_mask, validate_nm_mask
from .torch_integration import (
    QATConfig,
    QATPreparationReport,
    SmoothQuantLayerNormFold,
    SmoothQuantLinear,
    TorchActivationStatsCollector,
    TorchMagnitudePruner,
    TorchNMPruner,
    TorchSmoothQuantizer,
    TorchWandaPruner,
    collect_torch_activation_statistics,
    convert_qat,
    export_int8_bundle,
    fold_smoothquant_layer_norm,
    freeze_qat_observers,
    is_torch_available,
    prepare_qat,
    set_fake_quantization,
)
from .wanda import WandaPruner, WandaPruningResult, wanda_mask, wanda_scores

__all__ = [
    "AccuracyBudgetExceeded",
    "ActivationStatisticsCollector",
    "ActivationStatisticsTable",
    "BUILTIN_PROFILES",
    "BenchmarkResult",
    "ConfigurationError",
    "CalibrationTable",
    "ChannelStatistics",
    "ChannelStatsObserver",
    "DType",
    "EdgeOptError",
    "EntropyObserver",
    "MinMaxObserver",
    "HardwareProfile",
    "MemoryTier",
    "MagnitudePruner",
    "ModelSpec",
    "ModelProfile",
    "NMPruner",
    "NMPruningPattern",
    "NMPruningResult",
    "OperatorKind",
    "OperatorProfile",
    "OperatorSpec",
    "OptimizationConfig",
    "OptimizationPipeline",
    "OptimizationResult",
    "PolynomialPruningSchedule",
    "PruningStepResult",
    "QATConfig",
    "QATPreparationReport",
    "QualityAssessment",
    "QualityConstraint",
    "QuantizationConfig",
    "QuantizationParams",
    "RepresentativeCalibrator",
    "RooflineProfiler",
    "SmoothQuantConfig",
    "SmoothQuantLayerNormFold",
    "SmoothQuantLinear",
    "SmoothQuantResult",
    "SparseComputeCapability",
    "StrategyComparison",
    "StrategyMeasurement",
    "TensorSpec",
    "TorchActivationStatsCollector",
    "TorchMagnitudePruner",
    "TorchNMPruner",
    "TorchSmoothQuantizer",
    "TorchWandaPruner",
    "WandaPruner",
    "WandaPruningResult",
    "benchmark_callable",
    "apply_smoothquant",
    "collect_torch_activation_statistics",
    "convert_qat",
    "dequantize",
    "estimate_sparse_storage",
    "export_int8_bundle",
    "fake_quantize",
    "fold_smoothquant_layer_norm",
    "freeze_qat_observers",
    "is_torch_available",
    "load_builtin_profile",
    "measured_sparsity",
    "nm_mask",
    "operator_flops",
    "optimize_model_spec",
    "prepare_qat",
    "quantize",
    "set_fake_quantization",
    "smoothquant_scales",
    "validate_nm_mask",
    "wanda_mask",
    "wanda_scores",
]

__version__ = "0.1.0"
